module.exports = Object.freeze({
	TYPE: {
		CONNECT: 'CONNECT',
		NOTIFICATION: 'NOTIFICATION',
		EVENT: 'EVENT',
		COMMAND: 'COMMAND',
		WARNING: 'WARNING',
		ALERT: 'ALERT',
	},
	STATUS: {
		ONLINE: 'ONLINE',
		OFFLINE: 'OFFLINE',
	},
});
