module.exports = Object.freeze({
	TYPE: {
		CONNECT: 'CONNECT',
		NOTIFICATION: 'NOTIFICATION',
		EVENT: 'EVENT',
        COMMAND: 'COMMAND',
		SEARCH: 'SEARCH',
		LEARN: 'LEARN',
		WARNING: 'WARNING',
		ALERT: 'ALERT'
	},
	STATUS: {
		ONLINE: 'ONLINE',
		OFFLINE: 'OFFLINE',
	},
});
